//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTABILIDAD2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cuenta_contable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuenta_contable()
        {
            this.detalle_entrada_contable = new HashSet<detalle_entrada_contable>();
        }

        [Display(Name = "ID")]
        public int id { get; set; }
        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }
        [Display(Name = "Permite transaccion")]
        public bool permite_transaccion { get; set; }
        [Display(Name = "tipo de cuenta")]
        public int tipo_cuenta_id { get; set; }
        [Display(Name = "nivel")]
        public int nivel { get; set; }
        [Display(Name = "Cuenta mayor")]
        public int cuenta_mayor { get; set; }
        [Display(Name = "Balance")]
        public double balance { get; set; }
        [Display(Name = "Estado")]
        public bool estado { get; set; }
    
        public virtual tipo_cuenta tipo_cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_entrada_contable> detalle_entrada_contable { get; set; }
    }
}
