//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTABILIDAD2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detalle_entrada_contable
    {
        [Display(Name = "ID")]
        public int id { get; set; }

        [Display(Name = "Entrada contable")]
        public int entrada_contable_id { get; set; }
        [Display(Name = "Cuenta contable")]
        public int cuenta_contable_id { get; set; }
        [Display(Name = "Tipo de movimiento")]
        public string tipo_movimiento { get; set; }

        [Display(Name = "Monto")]
        public double monto { get; set; }
        [Display(Name = "Estado")]
        public bool estado { get; set; }

        [Display(Name = "Cuenta Contable")]

        public virtual cuenta_contable cuenta_contable { get; set; }
        [Display(Name = "Entrada contable")]
        public virtual entrada_contable entrada_contable { get; set; }
    }
}
