//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTABILIDAD2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class entrada_contable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public entrada_contable()
        {
            this.detalle_entrada_contable = new HashSet<detalle_entrada_contable>();
        }
        [Display(Name = "ID")]
        public int id { get; set; }
        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }
        [Display(Name = "Auxiliar ")]
        public int auxiliar_id { get; set; }
        [Display(Name = "Moneda")]
        public int moneda_id { get; set; }
        [Display(Name = "Estado")]
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_entrada_contable> detalle_entrada_contable { get; set; }
    }
}
