//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTABILIDAD2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONTABILIDAD2Entities : DbContext
    {
        public CONTABILIDAD2Entities()
            : base("name=CONTABILIDAD2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auxiliarr> auxiliarr { get; set; }
        public virtual DbSet<cuenta_contable> cuenta_contable { get; set; }
        public virtual DbSet<detalle_entrada_contable> detalle_entrada_contable { get; set; }
        public virtual DbSet<entrada_contable> entrada_contable { get; set; }
        public virtual DbSet<monedaa> monedaa { get; set; }
        public virtual DbSet<tipo_cuenta> tipo_cuenta { get; set; }
    }
}
